build:
  environment:
    php:
      version: "8.1"
checks:
  php:
    code_rating: true
    duplication: true
tools:
  external_code_coverage:
    runs: 1
  php_code_sniffer: true
  php_mess_detector: true
filter:
  paths: [src/*]
